# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1dab41774947e42c400d6bc578c97c4bf8759c0f60d68c88070c24df646496a3481f8cb708104b0f801f2fa6a52de6476f89064bb8ce97f4414ce92fd3bae894

test:
  secret_key_base: 0d022093581ae7c320ad2e3fabbef6560936946dbf75281cd18675b686ddbd9c84c43ae14ec0964504ac22094ddc1fc6687f5cc2bd3cc5aa49eebc1eca9d80ab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
